services:
  app:
    image: aswinj1/ssrconnect:latest
    container_name: ssrportal-web
    env_file:
      - .env            # loads variables from your .env file
    environment:
      #  You can still override or add more here if needed
      NODE_ENV: production
    volumes:
      - uploads-data:/app/public/uploads
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
    user: "1001:1001"


  postgres:
    image: postgres:alpine
    container_name: ssrportal-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  caddy:
    image: caddy:2
    container_name: ssrportal-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - uploads-data:/uploads  # Add this to share uploads with app
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - app

volumes:
  pgdata:
  caddy-data:
  caddy-config:
  uploads-data:  # Add this shared volume

